spring.application.name=finance-manager

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=9a722e695fb40ee312d88001657c70f8623b3f8a9e88a38d6d6e2a7b6b5b4a3c2b1a0
jwt.expiration=86400000

# Server Configuration
server.port=8080
